apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp.name" . }}
  labels:
    {{- include "mcp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mcp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8100
      targetPort: http
