---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-tokens
  namespace: insidertrack-staging
spec:
  encryptedData:
    MCP_TOKENS: AgB0Xd0eraAjhG0Pu3cK8qBs9SjoMRuHW1L2mgVwxCj4CdzLiUsIFLpGkAYkQq5hNxjmHhXSwbU+p+PLFpoxqfEOtZ7fmOnXYi79wg1tDpG5UzMIQtEjg7SkmV6JAhKP8TP1n8KMLzCDNNXkWAXJKkDp9jGZ37GlqNtcLUbWpxF78HzPaJuhHOjRAMgFZWF3kzKNfmmEZtFTbHTG/cuvgk06BL+uuQwIRqZuzOyLrSHH84yN6n3bXKgCSuek6nBkaMbMgU/c34cBYRr+Zeg47KQE1YA4yNlcP4jgiPXW4NwI4FGbAo00+UklQVTJiCVXY/TTAccoT6lbQ75y0bZuY7wvZWR0yMCF66UJrRPBm8qCnuqgqSw6T0et1ir542KI5Y1Rf37ridk+87PBHABV1idyj3WPXAlEaHY2oeXnSh4RREDHsWjsOYAPDAtj9yYi/JDo3/RusPBTmk8mlks4Lk6j3EcEG9nIsCzFAzaRfwbLazRueLdd+0Y1hKMKJppGZhTbpnolZPFtuqsGhWdlOMz0lKVe9ZkC1I4xjhfjqreb6/VoRAljU6IFlPNVyOvXEjuaoWh8n+a6LGtpmVwuNMQfvlFioY9XGLW2Ju3bW9c9GSaww+roRWmvBSP1WGUr0AROKuIKxaLFpaAVo8BrjG9GgFMDEemotFiBObXoIrmxPDKpFLPByPNgSN5pGSX1vPcGNhNFue3DRxB00Q8Rv64ME01dbdmGONR3DWlxCfKED7JVXIkAY+FYx2Lw/eOx292H8Nmfz+XTdXdtQxPi
  template:
    metadata:
      name: mcp-tokens
      namespace: insidertrack-staging
