---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insidertrack-db
  namespace: insidertrack-staging
spec:
  encryptedData:
    DB_PASSWORD: AgCYUOpg5S29JqYElznSYsyiV9z8USz2SpPnFGRinmpZmpoE/B5DJRucYlVQs29PbEIPlvqlHdufBH6CLNf2DCc/pJJZGolAJR4H3fmrDautmEhbKSXtbz5hZvkpWergn8c3rsFlzTsF6C22pV6iauM2AdNfAB+uSWgqdu78xXIA/g8/aK11IkPqI6k90VfEM6A93Hpc8ohcVhQcPyKsBxixd0y1h78CCY6lEBChI9IybQgsQyxYX080QKiq8LTLF2kT8o7WUdq33tGTeOMJgpHnt3S/b0oWymCoTfcXWLiXa16wXJo7UeBchWth57cQ4QNZgmjnyKqmdLWHltCRPxlpOYfh/CQN8HJaS5JZS8j6lbyDgbYCrxOdZZgrPS8sTwoAXOX7Ggaw725HrD+1R+9dnKgaUDZCW307XsMUmoYvpljdtgNh2BVR75CGvA3fNgsbmsz6PK0Dto/0iE1+3Dv+SDctARV1RuZsEZ6CNzdNS/CLrLuC0pT2d7ZeDRLjxVvxWB442Yx+kd4AroHnbJgEpnGKg4rhYaNd0JNAomXL7Wgot+5mIblABDnagiqFs9H/PDSjVj0HwTI946j7mdRaCKYMlu4PcfPqimIKFafX0O63X2ciHa9vKPQQg0KjrD0EmJTCe2os7ebmREB7/x3B2nQGudWGVLBiVC+/7zP40d9oR0ev/zaOQEsi+AtRvzDTuJWiYP5fe7D5TZ4ITT2pfJddLe8MXqtg7CjxpRDbGFcsmO2leFw2LeINIg2xB2Y=
  template:
    metadata:
      name: insidertrack-db
      namespace: insidertrack-staging
