---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insidertrack-app
  namespace: insidertrack-staging
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCK5LeKPPFEhlkaydmV2C6M1BUFLHPP94yjT/+yme6ivvlnTO+DdYvM7iGFL0MfgclRMhZFQW+YuxWF0HGsOQ6eM4SwkBLPoZmoUeqNtMB5XZAzrckmaTZi7GXnQK3NT6aGMFLIAopMbnnnM6iFFZ3zRyCT46cPQwEFyVJ2IF2MaaPoRK173A/IqN53G9LLfm2UJblZ2GF8fec+XjUjytn1nZ0OSSmFkGqFu223Wul7Ar1CRSPn5xqh9iaY0v636Y1mLOeUeZMhAoOmSEGOKB9f2FdH6TTCFJB/60qgHoFLSizwkWsYYVfbpUibynsHtiTD+BmCet7bud9tdVH44b+FTKfiKogNAhhZaRhFmGXawRMu5NqZVmfdcArpwWIdj7Vc+XE70SB191hE9JundtEZHb4Uh064TIid+Ng5IjD+m15nkatIZ1LWAVVd0hZ0Zb+EwZnwg/vr/baVIpSHQ4h2QIhkvl2Vw3C/4MJ287cXur8VNXutzO23OXPMMwkV3YhNK3xjfmzayTDs8HRguYsrvmgrCKPhO6HEvrOGCWiuK8g5KW7iTSfLwTDdtM2PDhJnOgSZQ8MfyDvJv47YNnbNH5zuIfTu7v4eyKRDeni9WezyIM9oLx/RELAVMTwjFKjZxTiOLmibn6zJZXNP9afMzlKzaQLtYPdvHWWcu/LFCM5f7sxJvrQHQKgzYBBAklT/12sBr7AJFdJ+d6XxZW9SHuqcpoYYphk=
  template:
    metadata:
      name: insidertrack-app
      namespace: insidertrack-staging
