---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lecture-notes-db
  namespace: lecture-notes-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBijltPhEREYY/Wpj83M0T+ZSG5KTYkVaUx467mpGfIlCrLdwdv4V4HUmV7xU4KrTTvyuNt3bEnMwz2YoVdri9kdjMbwGD1KWT6SVVx1v690ucPUSJ2hPFFngVSU6PpCariG96E2xNwUjLJ9z/wFkJ5PRDptn4Gys1GW3UOCtu424GNo+lYpSXwCKHdVHNZQ/xauUw/Fmn88rJaMjnLrx0X2Cpd3fAQxvreMpzlRrMKSXHE/y/UjDToFohVlR66juymKh2b0iZq376H+sUhH2h25z5vehbnZq7M6KPFnsvU5gBGfsKy3/tJxkoHr7fH1CRchNFa4zIJA2he3VzWUWzV0qicaehFMZvsS7Vc1trrZuJV00OXJjYyI7xpAWcGWFCjOxBsXiR2ETPCwjeVvhX/zTF8lFqV7S9cz2PA2gVnNZPD+Ph97Yz5EKIJSCfvdE0nS/wOtnmQz715q6Yr42NMkkXowhSHdUxLutPpTw4uUJdatfDQCfq66Lun0kpQesNKQFh2AuXY13xpTjAg0VPekUAsBTNhhnYDotS94G7zjjKFvm0SsFEBPT73Fy5A/tR+Ne71b7j29eyEFq4CV6SiZuawJBMH3sXDC40jO+hSqQUCQaBZ5ZBTfROsyOSwwfDIPaHGT/GnCOB6ziqKAr/FazlIVqAHRdnXyiW4/1m68oAle7Ykliav64sEXMYS63VxFKer5wJ6TdXaUu8DJ7j0+lpnp0SlNz7fGsQZmYQJJK0C/FvuFqTyFWHAoZ8ZyDA=
  template:
    metadata:
      name: lecture-notes-db
      namespace: lecture-notes-staging
