---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lecture-notes-app
  namespace: lecture-notes-staging
spec:
  encryptedData:
    SECRET_KEY: AgAMHVmeYyyUhLNWC4nn+5Oa+2gUQ3/NO8KAILtoDSm5mHyJE2bqop0IdrQ7wS5zAejCd6FaglkFCFbEkasSF/AVfAUUPb2FxPnWpQpAgSE90/L+CnXlHzMx7yy9evEXiQXYy/Ib0eW8knIc0bv83TXcHcgt41TorB/WceTHfWjpy4WYyZKdxYHElyQJA8XJkscsj+OoHLEfHRUO+8THvV28IZi5S+SpP0nSD66hI5BZ2G9xoYU7JJkUuZ7rHVR1JyuXQj5fH3t6uMkUvgjctZvMSVDuV+tkXPM1pvRaBIwEYhJ3Mb+zkvTd3dPNvvii6ZRaq+JW5NyY4fcSXxM2kQlZhDlpjW1p06xmYgj5Sbj0n415mzaDhWhOOlIM02wS8cvdGS4ydwHNu3SXXoRAHNj3yxff+C4SYFrrC0XL0mKA+QbCtf6R96bRM2jxM8zqslj/vL+KvUPMHVsMXfFDdXSIzF/xu0KJNt82OBjEfHZElH/C2I0mSb843PkY2IFKqUFq2p8yFPL1mA13gSUn8LtR/W9no4VKoj9WrN8DbrZ+zTX9bkUB6yuBgXm5O4ljmpIPkLaZw/WvFYeeRpZSI5Hay5uByZ8mZtjUYYXkwZ7hF5ueAsQAsp4jlvwfRjsM6P50bVXOMK65izvbBHqXxrJtOwcDOs2pu1w7rzkIvufwmahtImoNYXACHHFlzYHAAoQ9mYFbOpj8nq4LY1pMRCCk6XuMka+wKX9RQb9E9T6jThcUL5DPnpC9IYtsufOBc0pz8P2muKv/Q+8fD3I81aFp
  template:
    metadata:
      name: lecture-notes-app
      namespace: lecture-notes-staging
