---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lecture-notes-minio
  namespace: lecture-notes-staging
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgB1+KFOKh+eGx1dmdO2upIuyejGEvWi19GQashkJoiNr6K0gdZT29x0n95Hwm5Ddy9ajEnzcT+SjapDpx2hqonT8FGHNEkTxrRHaHM/7cZ7le7Q6Xku0PzAQs+t3p0golo9CIaVdWOZzCMEEdbcKJN2zSHetdsxFNZPbwc4vOPOUin+hTVD7QPeVeF8n9W/sinTIz1k4Hy8Nfb06Pu6ntgNmJE33RzAbljTpQk5sYDe/o6cgTufwC1u9xyy2MOzDIjSq6kcLJkv3h1DQCX3GM+sMVpN0nvNDu7jAJxmbKRm0p9csZQgV4cLbdvQEFm30B+Q1ejvRHbsUqnIJyx1dysQI7LAxJNZiLCN1dMkxUQL4TXECnDAk6w+9vuEPYJd0g/Wj8qO2oKECsmfMPyVX1F5EHAPNDjkwNRqSLWw4jiYEpHmhSRRZ7OaybrM+BRlcb8toH2LQQ1/1usFwM71fPSRHclP/noAmsUj0D7tCo9Fmt0DixnHxvD9NXOO5W4VBwxE7fHq3vVEsA4WMZXPNUctyQda8s1ZVHCaD7ybAKrEh5NHICxc2SdLvNSX++UT7DiKady8NOCdY3ZQUImTfmTNw62wBW0y8dr7+0czuKNfzV4q6My3RnzAeDfPg1TgESugzM/p+34+ayj9oyeWq1dm0yPnz8hPfQA9pAheFyaS1182uqCk0R+qiyIrf1PpXlc/8z9mhrCPI5k/yUlWG0KfESO2bauC2chCMSF9X9Lrr2Ko1eRpCDqj7zFlU64+Ofs=
    MINIO_ROOT_USER: AgAiicREfatyhlMRy1jiKT7C5WNoifdyGv8NUoI0LUf/6t4VmB/Sbuo6kQSK5E+rGwqFmle+WHvgvo8aoTWamVVjuQp1u+iVhnQKxDysQ20nFGTN2kVKYfVOWTudPeCBjPKmRHzPmKbgglWf1RLfTaq3Xb8gaUJLJoTCnCqNDjUpnPqmp64jpEAe+MpRtPhbFgPbajljG/nCgvbzNYcBgQo/ozKsWgzpSiw5HIn1nnHtyt6wvi4xWAq6unWP04T6c1oiXWf+J2FtJSBIeMeq+xcEbd/KzpVxDYpaVrl0MoXwTkTpAOXRP7MchMc/EMFLJYEu2yx5ZYClv9oN2H5kZKBc9uVGBpdwa0SvjJeRAG/Ue/jhB73W7DtS3YQLq1sAlIk70VCnWCqESyFA2zwnJZXHVqwKcg6+EtrbUfsNqjCiS8kS9seK2eaxGHGHC4sMVZS/+TAln9sUYXLnG4+mgkP08nPfbTHWpLogx3+IUA1rMDD1ofQ4aGVA0F4j3XH3okjEoMFhO2t23mKyrIiYw1XYqEo5tU1Yg/8argGmwe11E2kgvV6J47Bo2/nG6cBouA7P/PiPyVpLAvt0IZ9vC6PGOE3ZTZItu6X3C3RzVbNpOaA5fh4OE3GV4iKMvfb4H0+C6ElRcakJEMVXAKjDl/vZSt0EIao2jm+8xVFjG63lKfollw3+17p3uFoWQKh7Os6Kzj7Nq9ybepfIg6fLwTP/
  template:
    metadata:
      name: lecture-notes-minio
      namespace: lecture-notes-staging
