---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-git
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgBoWTPZ1hi6OAuYhGbNohyvbjHl6ZDotfPfj8RprdlUyIAlfqdgn3ByMV70YHwGjmqLfVO3VbQQ6JpTZbaFvkfgYzfKl0BS7jdYTYqR5n2i5JTOfwZak4+xznhZf7u6LZr/gRk0PULEFJCRRap31G9Ea2YblAvqVNEHxVb4SLZwVC+/huT8/gKD7FPrTooO63S3sfcn4bBQu0/PtTB38FVmJjfXSgyGBRxTh+Qqh5nfOACBemViCMFdTUEvSoxBNQ5fFSObq65n5fUcUKEV1IUpZQg9cTtLZ/BqhbvVsnvm6P3d7JUPsyQE+J7EhCmOllzl5R34ZXll5xtEEvyizZYBKc+4sE2sDzEygeCMm2Je4Tkp09G3nyr/L/NKpSa5RExoSY23YXbije0wyfPhyF0BeXwzKUSkYOGcHxSADJM2N4dG/4k0bhCSBiXQT/01PZ4wRjtPa9Ea7+4MjbXFGqQinuRHSSlT2SHI0jeoGXWAM7p01+2JvMMFCn4qSAbmswntfthGUXM9ORlXebNyjS55+Yaklf27YSItUsLIYWg0CzcodRVyQlKgrDxA119c+nuej+eTMCFDsCKmr0axu+Yjzp8+uWuaYkALrAaPK/F4q0LI83VgneVsqkItKt5BaNOC8zEQThXlVku4YQHpVQ8gLXPiLNwmvIRI3kCW7PGFytcLbEsTTqzcFZvcEoyQk8+8tccVYGTppMAQjksaMITzZTo1oeSmo32mTOHCYvhPSsH6QwSCWTewJL4r96XvTC98mlTZNQVIq44un6JEY+Ibsh78JdJzK60Prp375r85CFsxknMW0k1PQZMjzNTxBxlzKfc9TjL7NaVZwJbWk5Mtv+809yA5tvUl1qa0T87HsWq3xNSFvI97nJQyc2qk7koTeWCUOAqS4kFetxqnnxtSeb/dvva1Cq/7p4p5LIPMy1AUqtAb2LLQocycvq9nBYVyM4qc0VmGguvnn9d3Kt2zXptqcnW+cS5NsuBNALBl1v27GLV+tJhr7Hlrvg3Uwk3RA4MtV7dR0/juSxyi/P0C5ph7QjHgeVF5JpM+MYJGVdl2jFmOu/iR+KW2JVgcdJDCrsHBfEdU7P7HCpOOcjKjXVXgAqVK24xt1JGUVUg3rojTk3O4OVUwdQHcVdkjg1tiUptw2cuFdn0v9GmyjdH4axc0Ax4f16+c5cxPaskQ3FmEXo29NlMAxcZTemhfodITzXIg9a39VSKO5dayKykRogEjvz6SIo0Uwj5DlYHqP0dduwBXsci07Iy8Q7VgTGA=
  template:
    metadata:
      name: image-updater-git
      namespace: argocd
