---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBfwLy1/0aLq9hwiIpke8x5Eiw2pRyftkWqAbRkl3Ub5luewiT2suz4C37cYk9TU5YABz6lbD6OegxK3so1gJ9jT/310HMxcNKT4GoVvCGvb0oAoh2A/JYGzcT5n26owXhCid1ZzC9f8mRXatkiE+o4NKc61kjb26uTE6FNva6CI9P6gbHOVmxIXGchOM0vL7Djm70fFPVgKN6gGldHTeOM0sYXT1lHeAhfxHlLlyXtQaqYuqfc3wDgX+wtwVt/6bX2GreO4EBgBHE7l12IPCuH9hdF7cO6gs65EY6GpA7UJGpE63MExQeAC5hJ0jEDfKjpJZxCrYPRcfVthCOJUzqBqZrkOCOQ9Z0U1yUnW9s1exk2sy8CKTWQ3RluHW1yDbL/l5t/zxbuDahlHf9rtUOzahje8R+sfocdkTdyjftK/BYLqrlHAHjNncxmrxBI417TPrvqIRQRRObdKkylUSG9kP6eKgkh1dDAWxZF/1mjgy2xfQ+lsJUSr6i9BEgxASLahQXMkE1ynE65bFelADVL976qCHK/n+gvEpqpzIEONbik8sBwkggFlsuy6ruyub7V3bBmpswPHAIto4DfmXE4oOrb/oXU3dL3bAy8YScoopNTrrPHQieH47YuO7KoVc6QN5DFrRPG8A+Y2XyKNF+4UMUErXS4DvaLQXgntqYLlZ9qTMqAAlOS33gRKdFYEOk9lRL1z+mELLO7kcE+z8r7cBdzQc/FKkc=
    admin-user: AgAW92hwMov/wP1YyigaqL+RsR3pppJRfcS/FpG7H4T3ktKfGJqyctrbv4GvmqeUVeUQ/FFaKdcmZ46+XqamjlmuFie6qDm/HwdYXhLJtdva+T2zFoy+E7QZMXh+2zxH/WthPG+obcU6tZOB+Iu4eyPiFPrrep0wPkkHbAtfIpbZWzMq7mVKjjT0575QrYU2ouyMF7EDpCVix2rnAqrl8xSMgiNH9egIkd53LDa2e6rz2kfpoJ8a3Nr1Hxnv/jXwbbZW4UfIQlghAE/yGTRAFdzMyjndM2aVMkMhd3B68Z+Sj94yfIWgPu1uw3THVGA/i+X9dC4P6wDvI+RTKsw0bhACtQqg83R/ufUzFbrY5/+JfHgPcNblujHKLq6psXvQ32lN9qEKfYq/ejehJCuPSqKavbeinblPEfqF9LUr2TcHHitBc10I0EmFvjqY8KtngbS07j0gus1mTzP4guJBinriybbzCzlQ/3w/F8qToFdOaClEyLdwXTGmVX1eQDIH3gPkAplGRTSqA2LIAqrgly9e/hhHfFKmWXSQV1WT4cEZh7+u2pUgRsdNzML9noko3WB4pZXQ6L0q+M4A6S8m/QcYmkL/KmznV7ci0M1N6A0288H4Vy2wwYzPMnQfvo9smr8CBvqmq3fOplwpKNwR/PbeAEv9n1revoUHjEi2ir61CO+AARcsZ1fxdBUnHW10PXE5YRSPrQ==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
