---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCNAHGFxLlJ6YRSMC/A0AurDg/2LIqBot5/CAiYGTFKloK5gndm4km6HM6F7ObgYlNKan9RrIRgmr3iOEzSm6VJxQyv6yJqlpCp5vJOSFvEwg6rJMOLXNtqSPkghcSHFy6CppkgHA8SSnZGP1l24l7KTuezzMv7WKAs9RDYL59yAeC2RhdMv+vjFDqZ843gkWwXzoKMO4JCMQQ8OCY6bhxoZpxTX2LPioNigUJGptGknUDV/5LZe48M6+vMM89JTzXidEtADOWsg+Gvb1WWLruKw9SKiBuus1l+2IEhZ0Z2PnyKPrmIDsxvXtZuPE3taij3Zr1Ax2CpRfMoteRNbvUg7lfefWJvUf1N5xHZyTfdyvIGrjdONA7rfuHo6UL7Zc1ryqJiqGQs2EAga+g+MjjVOpJt6FsU6ZPzGCTUmbeCPBjH8nrRxzL12f+32SjQnY4f8DnzGuFfAdwBuC5/rf0neDCCqGIuqu/74jnBV428oP3FzeV5jDAU9G25DGvB60+f1TwvktWbKZr9ua3lciaAgDfpz4d1soSmEY0SxKbc8VuT3XT/W9O8I+qjFd3mtQTWanMGmuQD6CK7fnXCir2kQjOFf2Mivz86cREVMZ7a74XxInvfnB1aEp+jaavzLtqqhlvyRVPSJ/dasiAwfnc+JAx3k57/VtVdvh4pV2VYVCVmtEHQMSZ/ypx9q3VAFgREE9njVLvrhdy11/V+Zu01kw==
    client_secret: AgBF+9Wseo1K+nZdEYH21QR6yVf5+qWCG48nHhyExVUGYSm1t2VOGSa944EKERmI6Gx2toigr/REb/oPwJ/jZ1b6NoiorsiAQgpgEL5RQ0Kdp3KsnyYfW2AHsuB7KIJlM/LVG++UEsMWqOcUFEIlYwFOE8cAl6e0QpzAupOWBP9Daj0yLFJMCaUjAWIRCQxEpmcfFuUFT5jBHoeDhV0s7DHIg/Bxeule3ffhphMBEA+F8SKaZE4jqdyPJh/TByw3uG6FMOKiv9djjo0FyWaLgQK5FROBMJgzKhvqzymkS8+maMMEukpLXLuBinSuQaeNXrJi+zHTvAHvs4aNzEKz/s6TBDx976RKqpDgiOrHjGwhBeLWcoYxs9Cpy8uYK4DVI+7JGstB9XiL1pNdmXY7EgwSNsX5nRcYnL4v9EROC35GqR9qwEish8gCdRpTVEX88Hs5HeJriZEdmQQ0hF6+Xh7GuHV5VSkA4itku8umuKgH2WY1Q14r6kTn2sAN5rJmXP+2Kiwl7ZPklYQBcuJtHfR2aoCyO5+YUH10SZFTLZtHYZT1gLSPjzlknFCdq/VzprNGdXkzOBvWrbNgG0rwC4fEPZaNyNeGld8iHIeqPiSqfgZ8TjTHF32Iu0ADO5pkiJSFceMdj0BJ3uV62rhHkuIuVXcPEToV3sQwcl/n7V+/fyMuLcCO3IC0STi9RxLsdAvzmi6gvpnSM4dgoFrob/2Z+WW9UYSZ1B8NrxjyPPFAKgy4+y4vHGOedq3mwllvTY6JgfBWB2sG7TsKAmqIxJE=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
